name: Deploy Beta

on: workflow_dispatch

permissions:
    id-token: write
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Setup Yarn v3
              run: |
                corepack enable
                corepack prepare yarn@stable --activate
            - name: Install dependencies
              run: yarn install --immutable
            - name: Build
              run: yarn run build
            - name: Publish
              run: |
                  git config --global user.name 'BaklavaJS CICD'
                  git config --global user.email 'newcat@users.noreply.github.com'
                  echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
                  lerna version prerelease --preid beta --yes
                  lerna publish from-package --dist-tag next --yes
            - name: Build docs
              run: |
                  yarn run generate-api-docs
                  yarn run docs:build
            - name: Azure login
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Publish docs
              uses: azure/CLI@v1
              with:
                  inlineScript: |
                      az storage blob sync --account-name baklavajs -c '$web' -s "./docs/.vuepress/dist/"
            - name: Purge CDN endpoint
              uses: azure/CLI@v1
              with:
                  inlineScript: |
                      az cdn endpoint purge --content-paths "/*" --profile-name "baklavajs" --name "baklavajs" --resource-group "Private" --no-wait
            - name: Azure Logout
              run: az logout
              if: always()
